// Mocks generated by Mockito 5.4.0 from annotations
// in test_application/test/features/fact_trivia/presentation/bloc/cat_image_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_application/core/error/failure.dart' as _i6;
import 'package:test_application/features/fact_trivia/domain/enities/cat_image.dart'
    as _i7;
import 'package:test_application/features/fact_trivia/domain/repositories/cat_image_repository.dart'
    as _i2;
import 'package:test_application/features/fact_trivia/domain/usecases/get_cat_image.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCatImageRepository_0 extends _i1.SmartFake
    implements _i2.CatImageRepository {
  _FakeCatImageRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetCatImage].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCatImage extends _i1.Mock implements _i4.GetCatImage {
  MockGetCatImage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CatImageRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCatImageRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.CatImageRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.CatImage>> call(
          _i4.CatParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.CatImage>>.value(
            _FakeEither_1<_i6.Failure, _i7.CatImage>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.CatImage>>);
}
