// Mocks generated by Mockito 5.4.0 from annotations
// in test_application/test/features/fact_trivia/data/repositories/cat_image_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:test_application/features/fact_trivia/data/datasources/cat_image_remote_data_source.dart'
    as _i3;
import 'package:test_application/features/fact_trivia/data/models/cat_image_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCatImageModel_0 extends _i1.SmartFake implements _i2.CatImageModel {
  _FakeCatImageModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CatImageRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatImageRemoteDataSource extends _i1.Mock
    implements _i3.CatImageRemoteDataSource {
  MockCatImageRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CatImageModel> getCatImage() => (super.noSuchMethod(
        Invocation.method(
          #getCatImage,
          [],
        ),
        returnValue: _i4.Future<_i2.CatImageModel>.value(_FakeCatImageModel_0(
          this,
          Invocation.method(
            #getCatImage,
            [],
          ),
        )),
      ) as _i4.Future<_i2.CatImageModel>);
}
